### ISSUE TITLE
Solve Reverse Integer Problem

### ISSUE THREAD

**Issue by cycleandsandeep** [cycleandsandeep/Codepedia#12]

**Comment by nishantdub37** [comment]
@cycleandsandeep can u assign this to me?

**Comment by cycleandsandeep** [comment]
Sure, create .cpp solution file and write your code there as created for other questions.

**Comment by DeepAnsh210** [comment]
@cycleandsandeep Can i submit the solution in java?

**Comment by cycleandsandeep** [comment]
@DeepAnsh210 Go Ahead.

**Comment by itsparthchow** [comment]
Can i submit the code in python?
